### ISSUE TITLE
Documents for installation and configuration guide

### ISSUE THREAD

**Issue by curlyBaba** [alesanfra/lorawancloud#2]
Can you provide documents on the following:

- System requirement to run the server.
- Hardware requirements
- Installation and configuration guide.

**Comment by alesanfra** [comment]
Hi, thanks for your interest in lorawancloud!

There are no particular requirements to run this software, it is implemented in plain java and it should run on any java 7 JVM. For example, we successfully tested lorawancloud on a server with 2 GiB of ram and 2 vCPU, running ubuntu 14.04 and java jdk 7.
You can find other details on the architecture in chapter 3.2, 3.3 and 4 of the final report of my master thesis: https://github.com/alesanfra/lorawan-relay/blob/main/thesis.pdf

Please note that lorawancloud was developed from scratch for the research purposes described in my thesis, and it is provided as is. Feel free to modify it for your own purposes (as per the license) and open pull requests, any contribution is very much appreciated.
